// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbcommon

import (
	"database/sql"
	"time"
)

type Client struct {
	ID        int64
	Namespace string
	Name      string
	CreatedAt time.Time
}

type Session struct {
	ID                  int64
	SessionID           []byte
	UserID              sql.NullInt64
	AuthCode            string
	ClientID            int64
	PkceChallenge       string
	PkceChallengeMethod string
	State               string
	RedirectUri         string
	ExpiresAt           time.Time
	CreatedAt           sql.NullTime
}

type User struct {
	ID       int64
	Uuid     string
	Email    string
	Password string
}
